### ISSUE TITLE
Implement caching in the ClientProvider

### ISSUE THREAD

**Issue by TwinProduction** [TwinProduction/g8#1]
Implementing a cache with a configurable TTL as well as a configurable maximum size in ClientProvider could be very useful to help preventing unnecessary load on whatever service or infrastructure component ClientProvider's `getClientByTokenFunc` function is calling.

The implementation:
- Must be able to have a maximum cache size (e.g. 10000)
- Must be able to have a configurable TTL (e.g. 1 hour)
- Must be able to cache invalid tokens with a shorter entry TTL (e.g. 30 minutes)

Being the self-promoting person that I am, I think [TwinProduction/gocache](https://github.com/TwinProduction/gocache) would fit this role perfectly.

**Comment by ynden** [comment]
Hi Chris, I would like to give it a shot. 
Thanks
